### ISSUE TITLE
Not working on o3DS 11.5E

### ISSUE THREAD

**Issue by supersupersnivy97** [MrNbaYoh/notehax#2]
When I start the hacked flipnote, flipnote closes with a black screen then I go back to the home menu then 3ds has to restart with a "an error has occured..." message

**Comment by ghost** [comment]
Same here N3DS EUR

**Comment by penguij** [comment]
Exact same issue here, except without the error message and a continuous black screen until the A button is pressed, instead.
N3DS / EUR (UK) / 11.5.0-38E

**Comment by mck-9061** [comment]
Same issue here, when I tap the hacked flipnote it immediately freezes, then crashes to an error message which restarts the system.
O3DS / EUR (UK) / 11.5.0-38E

**Comment by bhaskar253** [comment]
I want to know that should I wait for getting proper notehax for flipnote version 1.0.1 on 11.5.0-38U  or there will be no further updates

**Comment by supersupersnivy97** [comment]
Fix: change language to French

Thanks MrNbaYoh!
