### ISSUE TITLE
N2DSXL 11.5.38U - Hanging at debug screen 

### ISSUE THREAD

**Issue by Lyriati** [MrNbaYoh/notehax#3]
![image](https://user-images.githubusercontent.com/17955898/30661695-6b73d672-9e0a-11e7-82f3-00840aa10696.png)
Hangs here, I have rop.bin and otherapp.bin

**Comment by yosh778** [comment]
Same here, with blue tactile screen
o2DS 11.5.38E, Flipnote 1.0.0

![img_20170920_214025](https://user-images.githubusercontent.com/2695804/30664153-10dd4f7a-9e4d-11e7-85e1-808f691c3d9b.jpg)

**Comment by Lyriati** [comment]
I've solved mine by attempting it multiple times, it seems unstable to launch but it works.

**Comment by PhanthomAvatar** [comment]
Same error , can anyone send me the infrastructure of the sd please? Thanks at all

**Comment by yosh778** [comment]
Never got it working, I formatted my SD card, reinstalled fresh, and I'm french so always had french anyway
I think it's because I have an o2DS, tried multiple times

**Comment by yosh778** [comment]
Ok didn't say anything, got it working after many many attempts ... XD

**Comment by PhanthomAvatar** [comment]
Same , usually works with internet

**Comment by yosh778** [comment]
indeed reconfigured internet at some point
Installed oothax now

**Comment by PhanthomAvatar** [comment]
Nah why? Homebrew without kernel backdoor is useless for me xD
