### ISSUE TITLE
N3DSXL EUR - Flipnote 1.0.1 - 11.5.0.38E

### ISSUE THREAD

**Issue by Cryru** [MrNbaYoh/notehax#4]
Upon opening the note Flipnote says that the note is corrupted and deletes it.

**Comment by 1mcuadros** [comment]
You need to have flipnote 1.0.0 ... So you can't do anything, because it's already patched men

**Comment by Cryru** [comment]
Oh...shit.

**Comment by My1** [comment]
is  there a way to get the old version running? I may have the old version, but the 3DS refuses to launch it.
